BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE budget_escalation_log CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE fashion_brands CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE fashion_brands (
    brand_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_name VARCHAR2(100) NOT NULL UNIQUE,
    country VARCHAR2(50) NOT NULL,
    year_founded NUMBER NOT NULL,
    creative_director VARCHAR2(100),
    allocated_budget NUMBER(15,2) NOT NULL,
    actual_spend NUMBER(15,2) NOT NULL
);

CREATE TABLE budget_escalation_log (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_name VARCHAR2(100),
    overrun_amount NUMBER(15,2),
    log_date DATE DEFAULT SYSDATE
);

INSERT INTO fashion_brands (brand_name, country, year_founded, creative_director, allocated_budget, actual_spend) VALUES ('Chanel', 'France', 1909, 'Virginie Viard', 2000000, 1950000);
INSERT INTO fashion_brands (brand_name, country, year_founded, creative_director, allocated_budget, actual_spend) VALUES ('Dior', 'France', 1946, 'Maria Grazia Chiuri', 1800000, 2200000);
INSERT INTO fashion_brands (brand_name, country, year_founded, creative_director, allocated_budget, actual_spend) VALUES ('Prada', 'Italy', 1913, 'Miuccia Prada & Raf Simons', 1500000, 1500000);
INSERT INTO fashion_brands (brand_name, country, year_founded, creative_director, allocated_budget, actual_spend) VALUES ('Gucci', 'Italy', 1921, 'Sabato De Sarno', 1700000, 1650000);
INSERT INTO fashion_brands (brand_name, country, year_founded, creative_director, allocated_budget, actual_spend) VALUES ('Versace', 'Italy', 1978, 'Donatella Versace', 1600000, 1750000);
INSERT INTO fashion_brands (brand_name, country, year_founded, creative_director, allocated_budget, actual_spend) VALUES ('Zara', 'Spain', 1975, 'Unknown', 800000, 950000);

COMMIT;

SET SERVEROUTPUT ON;

DECLARE
    TYPE brand_rec_type IS RECORD (
        br_name fashion_brands.brand_name%TYPE,
        br_country fashion_brands.country%TYPE,
        br_founded fashion_brands.year_founded%TYPE,
        br_director fashion_brands.creative_director%TYPE,
        br_alloc_budg fashion_brands.allocated_budget%TYPE,
        br_actual_spd fashion_brands.actual_spend%TYPE
    );

    TYPE brand_table_type IS TABLE OF brand_rec_type;
    l_brand_collection brand_table_type;
    l_is_heritage BOOLEAN;
    l_is_over_budget BOOLEAN;

BEGIN
    DBMS_OUTPUT.PUT_LINE('=== PARIS FASHION WEEK - BRAND AUDIT ===');
    DBMS_OUTPUT.PUT_LINE('');

    SELECT brand_name, country, year_founded, creative_director, allocated_budget, actual_spend
    BULK COLLECT INTO l_brand_collection
    FROM fashion_brands
    ORDER BY brand_name;

    FOR i IN 1..l_brand_collection.COUNT LOOP
        DBMS_OUTPUT.PUT_LINE('Processing: ' || l_brand_collection(i).br_name);
        l_is_heritage := FALSE;
        l_is_over_budget := FALSE;

        IF l_brand_collection(i).br_founded < 1920 THEN
            l_is_heritage := TRUE;
            DBMS_OUTPUT.PUT_LINE('   -> Heritage brand detected. Initiating protocol...');
            GOTO heritage_protocol;
        END IF;

        IF l_brand_collection(i).br_actual_spd > l_brand_collection(i).br_alloc_budg THEN
            l_is_over_budget := TRUE;
            DBMS_OUTPUT.PUT_LINE('   -> Budget overrun detected. Initiating escalation...');
            GOTO budget_escalation;
        END IF;

        GOTO finalize_brand;

        <<heritage_protocol>>
            DBMS_OUTPUT.PUT_LINE('   *** PROTOCOL: Priority runway slot assigned.');
            GOTO finalize_brand;

        <<budget_escalation>>
            DBMS_OUTPUT.PUT_LINE('   *** PROTOCOL: Escalated to Finance Committee.');
            INSERT INTO budget_escalation_log (brand_name, overrun_amount)
            VALUES (l_brand_collection(i).br_name, (l_brand_collection(i).br_actual_spd - l_brand_collection(i).br_alloc_budg));
            GOTO finalize_brand;

        <<finalize_brand>>
            DBMS_OUTPUT.PUT('   RESULT: ');
            IF l_is_over_budget THEN
                DBMS_OUTPUT.PUT('**OVER BUDGET**');
            ELSE
                DBMS_OUTPUT.PUT('On Budget');
            END IF;

            IF l_is_heritage THEN
                DBMS_OUTPUT.PUT(' | **HERITAGE BRAND**');
            END IF;
            DBMS_OUTPUT.PUT_LINE('');
            DBMS_OUTPUT.PUT_LINE('');
    END LOOP;
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('=== Audit Complete ===');
END;
/


SELECT brand_id, brand_name, country, year_founded, allocated_budget, actual_spend,
       (actual_spend - allocated_budget) as budget_difference
FROM fashion_brands
ORDER BY brand_name;

SELECT log_id, brand_name, overrun_amount, log_date
FROM budget_escalation_log
ORDER BY log_date;

SELECT 
    COUNT(*) as total_brands,
    COUNT(CASE WHEN year_founded < 1920 THEN 1 END) as heritage_brands,
    COUNT(CASE WHEN actual_spend > allocated_budget THEN 1 END) as over_budget_brands,
    SUM(allocated_budget) as total_allocated_budget,
    SUM(actual_spend) as total_actual_spend,
    SUM(actual_spend - allocated_budget) as total_overrun
FROM fashion_brands;

SELECT brand_id, brand_name, country, year_founded, allocated_budget, actual_spend,
       (actual_spend - allocated_budget) as budget_difference
FROM fashion_brands 
ORDER BY brand_name;

SELECT 
    brand_id as "ID",
    brand_name as "Brand",
    country as "Country", 
    year_founded as "Founded",
    allocated_budget as "Allocated",
    actual_spend as "Actual",
    (actual_spend - allocated_budget) as "Difference"
FROM fashion_brands 
ORDER BY brand_id;

SELECT 
    brand_id as "ID",
    brand_name as "Brand",
    country as "Country", 
    year_founded as "Founded",
    allocated_budget as "Allocated",
    actual_spend as "Actual",
    (actual_spend - allocated_budget) as "Difference"
FROM fashion_brands 
ORDER BY brand_id;

SELECT brand_id, brand_name, country, year_founded, allocated_budget, actual_spend
FROM fashion_brands;

SET PAGESIZE 50
SET LINESIZE 200
COLUMN brand_name FORMAT A20
COLUMN country FORMAT A15
COLUMN allocated_budget FORMAT 999,999,999
COLUMN actual_spend FORMAT 999,999,999
COLUMN budget_difference FORMAT 999,999,999

SELECT brand_id, brand_name, country, year_founded, allocated_budget, actual_spend,
       (actual_spend - allocated_budget) as budget_difference
FROM fashion_brands 
ORDER BY brand_name;






